export type Runtime = "node" | "python" | "go" | "java";
export type Shell = "bash" | "zsh" | "fish";
export type ExtraTool = "curl" | "wget" | "nano" | "vim" | "htop" | "jq";

export type ConfigOptions = {
  runtime: Runtime;
  version: "lts" | "latest";
  shell: Shell;
  git: boolean;
  ssh: boolean;
  extras: ExtraTool[];
};

export type GeneratedConfig = {
  curlCommand: string;
  scriptPreview: string;
  configId: string;
};

const RUNTIME_VERSIONS: Record<Runtime, Record<string, string>> = {
  node: { lts: "20", latest: "21" },
  python: { lts: "3.11", latest: "3.12" },
  go: { lts: "1.22", latest: "1.23" },
  java: { lts: "17", latest: "21" },
};

const RUNTIME_INSTALL: Record<Runtime, (version: string) => string> = {
  node: (v) => `# Install Node.js ${v}
pkg install -y nodejs-lts
node --version
npm --version`,

  python: (v) => `# Install Python ${v}
pkg install -y python
python --version
pip --version`,

  go: (v) => `# Install Go ${v}
pkg install -y golang
go version`,

  java: (v) => `# Install Java ${v}
pkg install -y openjdk-${v}
java --version`,
};

const SHELL_SETUP: Record<Shell, string> = {
  bash: `# Bash is default in Termux — nothing extra needed`,
  zsh: `# Install and set Zsh
pkg install -y zsh
chsh -s zsh`,
  fish: `# Install Fish shell
pkg install -y fish
chsh -s fish`,
};

function generateScript(options: ConfigOptions): string {
  const { runtime, version, shell, git, ssh, extras } = options;
  const runtimeVersion = RUNTIME_VERSIONS[runtime][version];

  const lines: string[] = [
    `#!/data/data/com.termux/files/usr/bin/bash`,
    `# Generated by Forge — forge.brgt.site`,
    `# Config: ${runtime} ${runtimeVersion} | ${shell} | ${new Date().toISOString().split("T")[0]}`,
    ``,
    `set -e`,
    `echo "🔥 Starting Forge setup..."`,
    ``,
    `# Update packages`,
    `echo "📦 Updating packages..."`,
    `DEBIAN_FRONTEND=noninteractive pkg update -y && pkg upgrade -y --force-confold`,
    ``,
    `# Grant storage access`,
    `termux-setup-storage`,
    ``,
  ];

  lines.push(RUNTIME_INSTALL[runtime](runtimeVersion));
  lines.push(``);

  if (shell !== "bash") {
    lines.push(SHELL_SETUP[shell]);
    lines.push(``);
  }

  if (git) {
    lines.push(`# Install Git`);
    lines.push(`pkg install -y git`);
    lines.push(`echo "Enter your Git username:"`);
    lines.push(`read GIT_NAME`);
    lines.push(`echo "Enter your Git email:"`);
    lines.push(`read GIT_EMAIL`);
    lines.push(`git config --global user.name "$GIT_NAME"`);
    lines.push(`git config --global user.email "$GIT_EMAIL"`);
    lines.push(`git config --global init.defaultBranch main`);
    lines.push(``);
  }

  if (ssh) {
    lines.push(`# Generate SSH key`);
    lines.push(`pkg install -y openssh`);
    lines.push(`echo "Enter your email for SSH key:"`);
    lines.push(`read SSH_EMAIL`);
    lines.push(`ssh-keygen -t ed25519 -C "$SSH_EMAIL" -f ~/.ssh/id_ed25519 -N ""`);
    lines.push(`echo ""`);
    lines.push(`echo "📋 Your public SSH key (add to GitHub):"`);
    lines.push(`cat ~/.ssh/id_ed25519.pub`);
    lines.push(``);
  }

  if (extras.length > 0) {
    lines.push(`# Extra tools`);
    lines.push(`pkg install -y ${extras.join(" ")}`);
    lines.push(``);
  }

  lines.push(`echo ""`);
  lines.push(`echo "✅ Forge setup complete!"`);
  lines.push(`echo "Built with forge.brgt.site"`);

  return lines.join("\n");
}

function generateConfigId(options: ConfigOptions): string {
  const parts = [
    options.runtime,
    options.version,
    options.shell,
    options.git ? "g" : "",
    options.ssh ? "s" : "",
    options.extras.join(""),
    Date.now().toString(36),
  ]
    .filter(Boolean)
    .join("-");
  return btoa(parts).replace(/[^a-zA-Z0-9]/g, "").slice(0, 10);
}

export function generateConfig(options: ConfigOptions): GeneratedConfig {
  const scriptPreview = generateScript(options);
  const configId = generateConfigId(options);
  const curlCommand = `curl -fsSL https://forge.brgt.site/api/config/${configId} | bash`;

  return {
    curlCommand,
    scriptPreview,
    configId,
  };
}

export const DEFAULT_OPTIONS: ConfigOptions = {
  runtime: "node",
  version: "lts",
  shell: "bash",
  git: true,
  ssh: true,
  extras: ["curl", "wget", "nano"],
};
    
